run-name: Deploy ${{ github.event.inputs.service }} to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Choose Service to Deploy"
        required: true
        default: backend
        type: choice
        options:
          - backend
          - frontend
          - chatbot

      environment:
        description: "Choose Environment to Deploy"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  information:
    name: Show Workflow Details
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Workflow Details
        run: |
          echo "Selected service: ${{ github.event.inputs.service }}"
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "Running on branch reference: ${{ github.ref}}

  code-quality:
    name: Check Code Formatting
    uses: ./.github/actions/format-action
    with:
      python-version: "3.11"

  unit-tests:
    name: Run Unit Tests
    uses: ./.github/actions/unit-test-action
    with:
      python-version: "3.11"
