name: Deploy
run-name: Deploy ${{ github.event.inputs.service }} to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Choose Service to Deploy"
        required: true
        default: backend
        type: choice
        options:
          - backend
          - frontend
          - chatbot

      environment:
        description: "Choose Environment to Deploy"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

env:
  AWS_DEFAULT_REGION: us-east-1
  PYTHON_VERSION: "3.11"

jobs:
  information:
    name: Show Workflow Details
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Workflow Details
        run: |
          echo "Selected service: ${{ github.event.inputs.service }}"
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "Running on branch reference: ${{ github.ref }}"

  code-quality:
    name: Check Code Formatting
    needs: information
    uses: ./.github/workflows/format.yml
    with:
      python-version: ${{ github.env.PYTHON_VERSION}}

  unit-tests:
    name: Run Unit Tests
    needs: information
    uses: ./.github/workflows/unit-tests.yml
    with:
      python-version: ${{ github.env.PYTHON_VERSION}}

  cdk-synth-diff:
    name: CDK Synth & Diff
    needs: ["code-quality", "unit-tests"]
    uses: ./.github/workflows/cdk-synth-diff.yml
    with:
      python-version: ${{ github.env.PYTHON_VERSION}}
      deployment-environment: ${{ github.event.inputs.environment }}
      service: ${{ github.event.inputs.service }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
